name: spatial-gnn
channels:
  - defaults
dependencies:
  - pip==23.3.1
  - python==3.10.18
  - pip:
    - numpy==2.2.6
    - pandas==2.3.1
    - scanpy==1.9.8
    - squidpy==1.2.3
    - torch==2.4.1
    - torch-geometric==2.6.1
