name: spatial-gnn
channels:
  - defaults
dependencies:
  - pip==25.1.1
  - python==3.10.0
  - pip:
    - numpy==2.2.6
    - pandas==2.3.0
    - scanpy==1.11.3
    - squidpy==1.6.5
    - torch==2.6.0
    - torch-geometric==2.6.1
